centers = {
    "MPG": ["mpg"],
    "CLCBIO": ["clcbio"],
    "PlatinumGenomes": ["platinumgenomes"],
    "MtSinai": ["mtsinai"],
    "Nebraska": ["nebraska"],
    "OsloUniversityHospital": ["oslo"],
    "DNAnexus": ["dnanexus"],
    "SevenBridges": ["sevenbridges"],
    "Rutgers": ["rutgers"],
    "BilkentUni": ["bilkent"],
    "Baylor": ["baylor"],
    "10XGenomics": ["10xgenomics"],
    "Broad": ["broad"],
    "Roche": ["roche", "bina"],
    "Bionano": ["bionano"],
    "BU": ["bu"],
    "Cornell": ["cornell"],
    "CSHL": ["cshl"],
    "NIST": ["nist"],
    "RealTimeGenomics": ["rtg"],
    "Sentieon": ["sentieon"],
    "CompleteGenomics": ["completegenomics"],
    "MDAnderson": ["mdanderson"],
    "Leicester": ["leicester"],
    "MSSM": ["mssm"],
    "Stanford": ["stanford"],
    "PacBio": ["pacbio"],
    "NHGRI": ["nhgri"],
    "NCBI": ["ncbi"],
    "SpiralGenomics": ["spiral"],
}
